import dotenv from 'dotenv';
import { z } from 'zod';
import crypto from 'crypto';

dotenv.config();

// Autogenerate fallback RSA keypair for dev/eval environments if placeholders are present
const generateFallbackRSAKeys = () => {
  const { publicKey, privateKey } = crypto.generateKeyPairSync('rsa', {
    modulusLength: 2048,
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  });
  return { publicKey, privateKey };
};

const envSchema = z.object({
  DATABASE_URL: z.string().url(),
  REDIS_URL: z.string().default('redis://localhost:6379'),
  NODE_ENV: z.enum(['development', 'production', 'test']).default('development'),
  PORT: z.string().transform(val => parseInt(val, 10)).default('4000'),
  JWT_PRIVATE_KEY: z.string().default('test_private_key_placeholder'),
  JWT_PUBLIC_KEY: z.string().default('test_public_key_placeholder'),
  ACCESS_TOKEN_TTL: z.string().default('15m'),
  REFRESH_TOKEN_TTL: z.string().default('30d'),
  COOKIE_DOMAIN: z.string().default('localhost'),
  CORS_ALLOWED_ORIGINS: z.string().default('http://localhost:3000,http://localhost:3001,https://app.workspace.com,https://review.workspace.com'),
  FRONTEND_URL: z.string().default('http://localhost:3000'),
  SMTP_HOST: z.string().optional(),
  SMTP_PORT: z.string().transform(val => parseInt(val, 10)).default('587'),
  SMTP_USER: z.string().optional(),
  SMTP_PASS: z.string().optional(),
  SMTP_FROM: z.string().default('Unified Workspace <noreply@workspace.com>'),
  LLM_API_KEY: z.string().optional(),
  S3_BUCKET: z.string().default('workspace-attachments'),
  S3_REGION: z.string().default('us-east-1'),
  S3_ACCESS_KEY: z.string().default('minio_access'),
  S3_SECRET_KEY: z.string().default('minio_secret'),
});

const parsed = envSchema.safeParse(process.env);

if (!parsed.success) {
  console.error('❌ Invalid environment variables detected at boot:', JSON.stringify(parsed.error.format(), null, 2));
  process.exit(1);
}

let { JWT_PRIVATE_KEY, JWT_PUBLIC_KEY, ...restEnv } = parsed.data;

if (JWT_PRIVATE_KEY === 'test_private_key_placeholder' || JWT_PUBLIC_KEY === 'test_public_key_placeholder') {
  if (restEnv.NODE_ENV === 'production') {
    console.error('❌ Fatal: Production deployment requires real RS256 JWT_PRIVATE_KEY and JWT_PUBLIC_KEY in secrets.');
    process.exit(1);
  }
  const keys = generateFallbackRSAKeys();
  JWT_PRIVATE_KEY = keys.privateKey;
  JWT_PUBLIC_KEY = keys.publicKey;
  console.log('⚠️ Notice: Autogenerated ephemeral RS256 keypair for local development/eval execution.');
}

export const env = {
  ...restEnv,
  JWT_PRIVATE_KEY,
  JWT_PUBLIC_KEY,
  corsOrigins: restEnv.CORS_ALLOWED_ORIGINS.split(',').map(o => o.trim()),
};
